=== PJBarbosa98/DAW2020/T2/project_record.dtd
<!ELEMENT	project_record		(title, header, workteam, abstract, deliverables)>

<!ELEMENT	title				(#PCDATA)	>
<!ELEMENT 	header				(key_name, pr_title, subtitle, start_date, end_date, supervisor)	>
<!ELEMENT	workteam			(#PCDATA)	>
<!ELEMENT 	abstract			(#PCDATA)	>
<!ELEMENT	deliverables		(#PCDATA)	>

<!ELEMENT key_name	(#PCDATA) >
<!ELEMENT pr_title	(#PCDATA) >
<!ELEMENT subtitle	(#PCDATA) >
<!ELEMENT start_date	(#PCDATA) >
<!ELEMENT end_date	(#PCDATA) >
<!ELEMENT supervisor	(#PCDATA) >


<!--
	FILE: project_record.dtd
	
	Defines fundamental structure for respective XML file(s).
	Can be used to validate XML files.
-->

=== PJBarbosa98/DAW2020/T2/project_record.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
	FILE: project_record.xml
	
	Project Record extended markup language (XML) file.
	Validated with `project_record.dtd`.
-->

<!-- Link to stylesheet `style.css` -->
<?xml-stylesheet href="style.css"?>
<!-- Link to DTD `project_record.dtd` -->
<!DOCTYPE project_record SYSTEM "project_record.dtd">

<project_record>
	<title>Project Record (Example)</title>

	<header>
		<key_name>
			KEY NAME: PR_Key_Name_001
		</key_name>

		<pr_title>
			TITLE: PR_Title_001
		</pr_title>

		<subtitle>
			SUBTITLE: PR_Subtitle_001
		</subtitle>
		
		<start_date>
			START DATE: PR_Start_Date_001
		</start_date>

		<end_date>
			End DATE: PR_End_Date_001
		</end_date>

		<supervisor>
			SUPERVISOR: PR_Supervisor_001
		</supervisor>
	</header>

	<workteam>
		WORKTEAM
	</workteam>

	<abstract>
		ABSTRACT
	</abstract>

	<deliverables>
		DELIVERABLES
	</deliverables>

</project_record>
